language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "node"
  - "stable"
before_install: "npm run-script travis-before-install"
script: "npm run-script travis-script"
before_script: "npm run-script travis-before-script"
after_script: "npm run-script travis-after-script"
